[package]
name = "parse_toml_rs"
version = "0.1.0"
authors = ["cmoran <christophermoran@ucsb.edu>"]
edition = "2018"

[dependencies]
libc = "0.2"

toml = "0.4.2"
serde_derive = ""
serde = ""


[lib]
name = "parse_toml_rs"
crate-type = ["staticlib","cdylib"]
