# Config file for SAMS farm mission
# requires the following fields:
#     - project_name = 'string'
#     - auv = 'string'
#     - point = [
#           {label='a',lat=x1,lon=y1},
#           {label='b',lat=x2,lon=y2},
#           {label='c',lat=xm,lon=ym},
#           {label='d',lat=xn,lon=yn}
#       ]
#           note: (must have an even number of points)
#
#     - tasks = ['label_string_m','label_string_2']
#           note:

#     - [start_point]
#         - location = 'string'
#         - lat = number
#         - lon = number # Note: haven't worked out using the GPS coordinate yet, doing as float vs u32 and converting

project_name = 'ucsb_sams'

auv = 'callinectes'

# Can have any number of points, but will be limited to a total of 32 tasks (64 ordered points in farm)
# For the moment, the waypoint field (lat,lon) are actually in local coordinates, not GPS. TO_DO, change that
waypoints = [
  {label='alpha',lat=50,lon=-50},
  {label='bravo',lat=50,lon=-150},
  {label='charlie',lat=75,lon=-175},
  {label='D',lat=75,lon=-25},
  {label='E',lat=100,lon=-25},
  {label='F',lat=125,lon=-175},
  {label='G',lat=150,lon=-175},
  {label='H',lat=175,lon=-50},
  {label='I',lat=150,lon=-10},
  {label='J',lat=100,lon=0},
  {label='K',lat=50,lon=0},
  {label='L',lat=0,lon=0},
]

# tasks are an ordered list (tasks appear in order of execution) of two strings, which correspond to the label
# strings attached to sets of listed points
# Limited to a maximum of 32 tasks, or 64 tasks total
# Okay, actually not going to say that tasks must be ordered pairs, just going to be a list of arbitary points
# the number of which can not exceed 64
tasks = [
    'alpha','bravo', # TASK 1
    'charlie','D', # TASK 2
    'E','F', # TASK 3
    'G','H'  # TASK 4
]

# lat = 34.408391, lon = -119.839120
# Is a Rust GeoCoor struct, {location,lat,lon}
# [start_point] should be placed last in the toml file to prevent other fields being
# considered as part of its fields
[start_point]
  label = 'Goleta beach'
  lat = 34408391
  lon = -119839120
