[package]
name = "convert-to-csv"
version = "0.1.0"
authors = ["chrism"]
edition = "2018"

[dependencies]
libc = "0.2"

image = "0.23"
ndarray = "0.12.1"
ndarray-csv = "0.5.1"
csv = "1.1"


[lib]
name = "image_to_csv_rs"
crate-type = ["staticlib","cdylib"]
